Fix OIDC logout URL
ArkCase/ark_helm_charts pull request #37
Opened 2024-07-18 20:44 UTC by david-oc-miller

Fixed the logout URL in src/app/charts/core/files/secrets/tpl/arkcase-oidc.yaml.

Probably I didn't update the right Chart.yaml files.  Since I changed only a file in src/app/charts/core, does that mean I only increment the version in src/app/charts/core/Chart.yaml?

2024-07-18 21:12 UTC, drivera-armedia requested changes
Should probably remove the file `src/app/charts/common-0.7.21.tgz` and let it be re-created by the `publish-chart` script to ensure you use the exact same file that's in the repository. This will also likely modify the PR to remove the requested binary file update.

Also, the chart version for app (i.e. in `src/app/Chart.yaml`) should also be bumped up.

2024-07-18 21:12 UTC, drivera-armedia commented on src/app/charts/common-0.7.21.tgz
I wonder why this binary file got updated ... did you run an `update-chart common` first?

2024-07-19 14:48 UTC, david-oc-miller commented on src/app/charts/common-0.7.21.tgz
I run update-chart all the time... is it more sensible to change the chart version first, before I change a file, and also change the chart version in any Chart.yaml from a higher folder?  And update-chart only then.

I'd rather not publish-chart until the MR is reviewed and approved; so is it better not to commit any tgz changes in in the initial MR?

2024-07-19 14:52 UTC, david-oc-miller commented
I've been in my morning meetings, no time to address your comments yet :-( is it OK now?

2024-07-19 14:53 UTC, drivera-armedia commented
> I've been in my morning meetings, no time to address your comments yet :-( is it OK now?

I did some fixes myself, for expediency's sake. It should be OK to merge now.

2024-07-19 14:55 UTC, drivera-armedia commented on src/app/charts/common-0.7.21.tgz
`update-chart` is useful for development, but you generally don't need to use it if you're not actively modifying the `common` chart.

The right way to do this would have been to, instead, use `publish-chart`. However, this would necessitate an update to the `app` chart's version (in `src/app/Chart.yaml`) to avoid confusion/clobbering the existing release of the same chart.

Does that make sense?

I can make some time to walk you through how I do it, if you like.

2024-07-19 14:55 UTC, merged

2024-07-19 14:57 UTC, david-oc-miller commented on src/app/charts/common-0.7.21.tgz
Sure thanks... so if I don't run the github CLI commands, publish-chart doesn't affect anyone else?